CREATE TABLE IF NOT EXISTS BEER_STOCK_ORDER (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  BEER_NAME VARCHAR(255) NOT NULL,
  QUANTITY INTEGER,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;